version: "3.8"
services:
  reader:
    image: "ghcr.io/gldeng/fireaelf-docker-build:4bb3eab"
    command:
      - "--config-file"
      - ""
      - "start"
      - "reader-node"
      - "--common-one-block-store-url"
      - "${DATA_PATH:-file:///data}/one-blocks"
      - "--reader-node-path"
      - "AElf.Launcher"
      - "--reader-node-arguments"
      - "--data-directory /data/node"
    ports:
      - "8000:8000"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app
      - ASPNETCORE_ENVIRONMENT=LocalTestNode
    volumes:
      - "./fireaelf-data:/data"
      - "./Logs:/app/Logs"
      - "./start-aelf-node:/app/AElf.Launcher"
      - "./appsettings.json:/app/appsettings.json"
      - "./appsettings.LocalTestNode.json:/app/appsettings.LocalTestNode.json"
      - "./appsettings.MainChain.MainNet.json:/app/appsettings.MainChain.MainNet.json"
      - "./W1ptWN5n5mfdVvh3khTRm9KMJCAUdge9txNyVtyvZaYRYcqc1.json:/root/.local/share/aelf/keys/W1ptWN5n5mfdVvh3khTRm9KMJCAUdge9txNyVtyvZaYRYcqc1.json"

  merger:
    image: "ghcr.io/gldeng/fireaelf-docker-build:4bb3eab"
    command:
      - "--config-file"
      - ""
      - "start"
      - "merger"
      - "--common-one-block-store-url"
      - "${DATA_PATH:-file:///data}/one-blocks"
      - "--common-merged-blocks-store-url"
      - "${DATA_PATH:-file:///data}/merged-blocks"
      - "--common-forked-blocks-store-url"
      - "${DATA_PATH:-file:///data}/forked-blocks"
    volumes:
      - "./fireaelf-data:/data"

  relayer:
    image: "ghcr.io/gldeng/fireaelf-docker-build:4bb3eab"
    command:
      - "--config-file"
      - ""
      - "start"
      - "relayer"
      - "--common-one-block-store-url"
      - "${DATA_PATH:-file:///data}/one-blocks"
      - "--relayer-source"
      - "${READER_IP:-reader}:10010"
    volumes:
      - "./fireaelf-data:/data"

  firehose:
    image: "ghcr.io/gldeng/fireaelf-docker-build:4bb3eab"
    command:
      - "--config-file"
      - ""
      - "start"
      - "firehose,substreams-tier1,substreams-tier2"
      - "--common-live-blocks-addr"
      - "--common-first-streamable-block=1"
      - "--substreams-state-bundle-size=10"
      - "--common-one-block-store-url"
      - "${DATA_PATH:-file:///data}/one-blocks"
      - "--common-merged-blocks-store-url"
      - "${DATA_PATH:-file:///data}/merged-blocks"
      - "--common-forked-blocks-store-url"
      - "${DATA_PATH:-file:///data}/forked-blocks"
      - "--common-live-blocks-addr"
      - "${RELAYER_IP:-relayer}:10014"
      - "--advertise-chain-name"
      - "aelf"
      - "--advertise-block-id-encoding"
      - "hex"
    ports:
      - "10015:10015"
      - "10016:10016"
    volumes:
      - "./fireaelf-data:/data"