version: "3.8"
services:
  reader:
    image: "fireaelf"
    command:
      - "--config-file"
      - ""
      - "start"
      - "reader-node"
      - "--common-one-block-store-url"
      - "file:///data/one-blocks"
      - "--reader-node-path"
      - "AElf.Launcher"
      - "--reader-node-arguments"
      - "--data-directory /data/node"
      - "--advertise-chain-name"
      - "aelf"
      - "--advertise-block-id-encoding"
      - "hex"
    volumes:
      - "./fireaelf-data:/data"
      - "./Logs:/app/Logs"
      - "./start-aelf-node:/app/AElf.Launcher"
      - "./appsettings.json:/app/appsettings.json"
      - "./appsettings.MainChain.MainNet.json:/app/appsettings.MainChain.MainNet.json"

  merger:
    image: "fireaelf"
    command:
      - "--config-file"
      - ""
      - "start"
      - "merger"
      - "--common-one-block-store-url"
      - "file:///data/one-blocks"
      - "--common-merged-blocks-store-url"
      - "file:///data/merged-blocks"
      - "--common-forked-blocks-store-url"
      - "file:///data/forked-blocks"
    volumes:
      - "./fireaelf-data:/data"

  relayer:
    image: "fireaelf"
    command:
      - "--config-file"
      - ""
      - "start"
      - "relayer"
      - "--common-one-block-store-url"
      - "file:///data/one-blocks"
      - "--relayer-source"
      - "reader:10010"
    volumes:
      - "./fireaelf-data:/data"

  firehose:
    image: "fireaelf"
    command:
      - "--config-file"
      - ""
      - "start"
      - "firehose"
      - "--common-one-block-store-url"
      - "file:///data/one-blocks"
      - "--common-merged-blocks-store-url"
      - "file:///data/merged-blocks"
      - "--common-forked-blocks-store-url"
      - "file:///data/forked-blocks"
      - "--common-live-blocks-addr"
      - "relayer:10014"
      - "--advertise-chain-name"
      - "aelf"
      - "--advertise-block-id-encoding"
      - "hex"
    ports:
      - "10015:10015"
    volumes:
      - "./fireaelf-data:/data"